#
# USAGE:
# $> docker-compose up
#

version: "2.1"

services:
  db:
    image: "postgres:9.6-alpine"
    environment:
      POSTGRES_USER: "${PGUSER:-postgres}"
      POSTGRES_PASSWORD: "${PGPASSWORD:-postgres}"
      PGUSER: "${PGUSER:-postgres}"
      PGPASSWORD: "${PGPASSWORD:-postgres}"
    ports:
      - "127.0.0.1:${PGPORT:-5432}:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"

  openapi:
    image: "marciocamurati/redoc"
    ports:
      - "127.0.0.1:4001:80"
    volumes:
      - "./apps/calgy_api/doc:/usr/share/nginx/html/data"

  web:
    build: "."
    environment:
      MIX_ENV:
      PGUSER: "${PGUSER:-postgres}"
      PGPASSWORD: "${PGPASSWORD:-postgres}"
      PGDATABASE: "${PGDATABASE:-calgy_dev}"
      PGHOST: "db"
      API_HOST: "${API_HOST:-localhost}"
    entrypoint: "bin/wait-for-db.sh"
    command: ["mix", "phx.server"]
    links:
      - db
    ports:
      - "127.0.0.1:${API_PORT:-4000}:4000"
    volumes:
      - ".:/app"
