#%RAML 1.0
title: "Calgy API"
version: 1
baseUri: http://api.calgy.org
mediaType: application/json

types:
  uuid:
    type: string
    pattern: "^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$"

  Event:
    type: object
    properties:
      id:
        type: uuid
        require: true
        example: "96ce421b-c9bb-4322-9d26-fbf403be43be"
      title:
        type: string
        required: true
        maxLength: 100
        example: "Mission to Mars - Liftoff!"
      description:
        type: string
        required: false
        maxLength: 5000
        example: >
          Join us for an amazing launch event filled with disco music from
          the world's largest rocket-mounted speakers. Liftoff is at 10:47,
          but the music won't stop till we get to Mars!
      start_at:
        type: datetime
        required: true
        example: "2022-08-17T14:00:00Z"
      end_at:
        type: datetime
        required: false
        example: "2022-08-17T15:00:00Z"


  PendingCalendar:
    type: object
    properties:
      id:
        type: uuid
        required: true
        example: "b376e8ff-b222-4559-a0e7-f344e505cee8"
      state:
        type: string
        required: true
        enum: [ "pending" ]
        example: "pending"
      title:
        type: string
        required: false
        maxLength: 100
        example: "Your Calendar"
      description:
        type: string
        required: false
        maxLength: 2000
        example: "The calendar that started evolving."
      public_url:
        type: string
        required: true
        description: "Public URL for retrieving details of a calendar. Read-only."
        example: "http://api.calgy.org/calendars/b376e8ff-b222-4559-a0e7-f344e505cee8"

  NewPendingCalendar:
    type: PendingCalendar
    properties:
      admin_url:
        type: string
        required: true
        description: >
          Admin URL for making changes to a calendar. This URL is considered
          a secret and is only returned when the calendar is first created.
        example: "http://api.calgy.org/calendars/413cd8cf-71f0-47a0-8ce4-644a95dba69e;admin"

  NotFoundError:
    type: object
    properties:
      error:
        type: string
        example: "not found"

  ValidationError:
    type: object
    properties:
      path:
        type: string
        example: "#/title"
      code:
        type: string
        example: "too_long"

  ValidationErrors:
    type: object
    properties:
      errors:
        type: ValidationError[]
        minItems: 1


/calendars:
  post:
    description: "Create a new calendar."

    body:
      example: |
        {}
    responses:
      201:
        headers:
          location:
            type: string
            description: >
              Location of the created calendar resource. This is the same URL
              as returned by the `admin_url` property and should be considered
              a secret. As the API develops, additional ways of authenticating
              will become possible.
            example: "http://api.calgy.org/calendars/413cd8cf-71f0-47a0-8ce4-644a95dba69e;admin"
        body:
          type: NewPendingCalendar

  /{id}:
    delete:
      description: "Delete an existing calendar."

      responses:
        204:
          body: ""
        404:
          body:
            type: NotFoundError

    get:
      description: "Retrieve an existing calendar."

      responses:
        200:
          body:
            type: PendingCalendar
        404:
          body:
            type: NotFoundError

    put:
      description: "Update a calendar."

      body:
        type: PendingCalendar

      responses:
        200:
          body:
            type: PendingCalendar
        404:
          body:
            type: NotFoundError
        422:
          body:
            type: ValidationErrors

    /events:
      post:
        description: "Create a new event."

        body:
          example: |
            {
              "title": "Mission to Mars - Liftoff!",
              "start_at": "2022-08-17T14:00:00Z",
              "end_at": "2022-08-17T15:00:00Z",
              "description": "Join us for an amazing launch event filled with disco music from the world's largest rocket-mounted speakers. Liftoff is at 10:47, but the music won't stop till we get to Mars!"
            }
        responses:
          201:
            headers:
              location:
                type: string
                description: >
                  Location of the created event resource.
                example: "http://api.calgy.org/events/96ce421b-c9bb-4322-9d26-fbf403be43be"
            body:
              type: Event
          404:
            body:
              type: NotFoundError
          422:
            body:
              type: ValidationErrors


/events:
  /{id}:
    get:
      description: "Retrieve an existing event."

      responses:
        200:
          body:
            type: Event
        404:
          body:
            type: NotFoundError

    put:
      description: "Update an event."

      body:
        type: Event

      responses:
        200:
          body:
            type: Event
        404:
          body:
            type: NotFoundError
        422:
          body:
            type: ValidationErrors
